<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CodeSquad.Common.Structures" Version="2.2.9" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RestSharp" Version="112.1.0" />
		<PackageReference Include="Serilog.Sinks.Http" Version="9.0.0" />
		<PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
		<PackageReference Include="System.ServiceModel.Http" Version="8.1.2" />
		<PackageReference Include="System.ServiceModel.NetTcp" Version="8.1.2" />
		<PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Persistence\Persistence.csproj" />
	  <ProjectReference Include="..\src\NotificationService.Core\Domain.csproj" />
	</ItemGroup>
	
</Project>
