// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotificationService.Infrastructure.Data;

#nullable disable

namespace NotificationService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(NotificationDbContext))]
    [Migration("20260918120915_InitialRelationalChannelConfiguration")]
    partial class InitialRelationalChannelConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NotificationService.Core.Entities.ConditionalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpectedMinCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Expression")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SqlQuery")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("ConditionalRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ExpectedMinCount = 1,
                            Expression = "total_pendientes > 0",
                            Name = "Verificar si hay filas retenidas",
                            Type = 1
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.DataSourceConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionStringOrUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtraConfigJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DataSources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionStringOrUrl = "Data Source=notification_service.db",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Base de Datos SQLite Interna / Demo",
                            Type = 2
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.ExecutionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConditionEvaluated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConditionResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataRowsFetched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostExecutionDetails")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedSubject")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetRecipient")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExecutionLogs");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelTypeId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelTypeId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Servidor SMTP Principal",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            ChannelTypeId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Webhook Sistema Externo",
                            Type = 2
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationChannelSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("BoolValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IntValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SettingDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StringValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SettingDefinitionId");

                    b.HasIndex("ChannelId", "SettingDefinitionId")
                        .IsUnique();

                    b.ToTable("ChannelSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 1,
                            StringValue = "smtp.gmail.com",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IntValue = 587,
                            SettingDefinitionId = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 3,
                            StringValue = "demo@gmail.com",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 5,
                            StringValue = "no-reply@empresa.com",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            BoolValue = true,
                            ChannelId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 6,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 10,
                            StringValue = "https://webhook.site/demo-notification",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            ChannelId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            SettingDefinitionId = 11,
                            StringValue = "POST",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationChannelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChannelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "EMAIL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "Email"
                        },
                        new
                        {
                            Id = 2,
                            Code = "SMS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "SMS"
                        },
                        new
                        {
                            Id = 3,
                            Code = "WEBHOOK",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            Name = "Webhook"
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConditionalRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CronExpression")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataQuery")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DataSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PostExecutionActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueryParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipientExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("ConditionalRuleId");

                    b.HasIndex("DataSourceId");

                    b.HasIndex("PostExecutionActionId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationSettingDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChannelTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSensitive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelTypeId", "Code")
                        .IsUnique();

                    b.ToTable("SettingDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelTypeId = 1,
                            Code = "SMTP_HOST",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "SMTP Host"
                        },
                        new
                        {
                            Id = 2,
                            ChannelTypeId = 1,
                            Code = "SMTP_PORT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 2,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "SMTP Port"
                        },
                        new
                        {
                            Id = 3,
                            ChannelTypeId = 1,
                            Code = "SMTP_USERNAME",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "SMTP Username"
                        },
                        new
                        {
                            Id = 4,
                            ChannelTypeId = 1,
                            Code = "SMTP_PASSWORD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = true,
                            Name = "SMTP Password"
                        },
                        new
                        {
                            Id = 5,
                            ChannelTypeId = 1,
                            Code = "FROM_ADDRESS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "From Address"
                        },
                        new
                        {
                            Id = 6,
                            ChannelTypeId = 1,
                            Code = "USE_SSL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 3,
                            Enabled = true,
                            IsRequired = false,
                            IsSensitive = false,
                            Name = "Use SSL"
                        },
                        new
                        {
                            Id = 7,
                            ChannelTypeId = 2,
                            Code = "PROVIDER_URL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "Provider URL"
                        },
                        new
                        {
                            Id = 8,
                            ChannelTypeId = 2,
                            Code = "API_KEY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = true,
                            Name = "API Key"
                        },
                        new
                        {
                            Id = 9,
                            ChannelTypeId = 2,
                            Code = "SENDER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "Sender"
                        },
                        new
                        {
                            Id = 10,
                            ChannelTypeId = 3,
                            Code = "URL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "Webhook URL"
                        },
                        new
                        {
                            Id = 11,
                            ChannelTypeId = 3,
                            Code = "HTTP_METHOD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = true,
                            IsSensitive = false,
                            Name = "HTTP Method"
                        },
                        new
                        {
                            Id = 12,
                            ChannelTypeId = 3,
                            Code = "TIMEOUT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 2,
                            Enabled = true,
                            IsRequired = false,
                            IsSensitive = false,
                            Name = "Timeout"
                        },
                        new
                        {
                            Id = 13,
                            ChannelTypeId = 3,
                            Code = "AUTH_TYPE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = false,
                            IsSensitive = false,
                            Name = "Auth Type"
                        },
                        new
                        {
                            Id = 14,
                            ChannelTypeId = 3,
                            Code = "AUTH_TOKEN",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataType = 1,
                            Enabled = true,
                            IsRequired = false,
                            IsSensitive = true,
                            Name = "Auth Token"
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ChannelType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BodyTemplate = "<h2>Hola {{ usuario_nombre }}</h2><p>Tienes <strong>{{ total_pendientes }}</strong> tareas pendientes por procesar.</p><ul>{% for item in items %}<li>{{ item.titulo }} - Status: {{ item.estado }}</li>{% endfor %}</ul>",
                            ChannelType = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Email Alerta Pendientes",
                            SubjectTemplate = "Atención: Tienes {{ total_pendientes }} tareas pendientes"
                        },
                        new
                        {
                            Id = 2,
                            BodyTemplate = "{\"event\":\"PENDING_ITEMS_ALERT\",\"total\":{{ total_pendientes }},\"timestamp\":\"{{ now }}\"}",
                            ChannelType = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Webhook Notification Payload",
                            SubjectTemplate = "ALERTA_WEBHOOK"
                        });
                });

            modelBuilder.Entity("NotificationService.Core.Entities.PostExecutionAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActionType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DataSourceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SqlQuery")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSourceId");

                    b.ToTable("PostExecutionActions");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.ConditionalRule", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.DataSourceConfig", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId");

                    b.Navigation("DataSource");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationChannel", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.NotificationChannelType", "ChannelType")
                        .WithMany()
                        .HasForeignKey("ChannelTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChannelType");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationChannelSetting", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.NotificationChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotificationService.Core.Entities.NotificationSettingDefinition", "SettingDefinition")
                        .WithMany()
                        .HasForeignKey("SettingDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("SettingDefinition");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationJob", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.NotificationChannel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotificationService.Core.Entities.ConditionalRule", "ConditionalRule")
                        .WithMany()
                        .HasForeignKey("ConditionalRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotificationService.Core.Entities.DataSourceConfig", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotificationService.Core.Entities.PostExecutionAction", "PostExecutionAction")
                        .WithMany()
                        .HasForeignKey("PostExecutionActionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NotificationService.Core.Entities.NotificationTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("ConditionalRule");

                    b.Navigation("DataSource");

                    b.Navigation("PostExecutionAction");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.NotificationSettingDefinition", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.NotificationChannelType", "ChannelType")
                        .WithMany()
                        .HasForeignKey("ChannelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelType");
                });

            modelBuilder.Entity("NotificationService.Core.Entities.PostExecutionAction", b =>
                {
                    b.HasOne("NotificationService.Core.Entities.DataSourceConfig", "DataSource")
                        .WithMany()
                        .HasForeignKey("DataSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSource");
                });
#pragma warning restore 612, 618
        }
    }
}
